name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore ranant.csproj

      - name: Build solution
        run: msbuild ranant.csproj /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ranant
          path: bin/Release/ranant.exe

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: bin/Release/ranant.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}